import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import { Button, Card, Grid, TextField } from "@material-ui/core";
import SideBar from "./../components/Sidebar";
import OverLay from "./../components/overlay/overlay";
import { useAppSelector } from "./../redux/hook";
import HeaderSearch from "./../components/Header/HeaderSearch";
import style from "./../styles/layout/header/Header.module.scss";
import Carousel from "../components/Carousel";
import HomeBody from "../components/HomeBody/HomeBody";

export default function Home() {
  const { isOpenSideBar, isOpenSearchMobile } = useAppSelector(
    (state) => state.uiReducer
  );

  return (
    <div className={styles.home}>
      <Head>
        <title> Thành Shop </title>{" "}
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
        />
      </Head>
      <Carousel />
     
      
        <div style={{background:'violet',alignItems:'center',padding:0,marginRight:0}}>
        <HomeBody />
        </div>

      
      <SideBar />
      <OverLay />
      <div
        className={`${style.header__searchMobile} ${
          !isOpenSearchMobile && style.header__searchMobileAppear
        }`}
      >
        <HeaderSearch />
      </div>
      <h1> Alo </h1>{" "}
    </div>
  );
}
