import Head from "next/head";
import { useState } from "react";
import Carousel from "../components/Carousel";
import ProductCategory from "../components/productCategory";
import style from "../styles/Home.module.scss";
import { useAppSelector } from "./../redux/hook";
import AutorenewIcon from "@material-ui/icons/Autorenew";
import LocalShippingIcon from "@material-ui/icons/LocalShipping";
import PaymentIcon from "@material-ui/icons/Payment";
import WatchLaterIcon from "@material-ui/icons/WatchLater";
import { Grid } from "@material-ui/core";

export default function Home() {
  return (
    <div className={style.home}>
      <Head>
        <title> Thành Shop </title>{" "}
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Carousel />
      <Grid container className={style.service}>
        <Grid item sm={6} md={3} xs={6}>
          <div className={style.serviceItem}>
            <LocalShippingIcon className={style.icon} />{" "}
            <span className={style.title}>Miễn phí vận chuyển</span>
          </div>
        </Grid>
        <Grid item sm={6} md={3} xs={6}>
          <div className={style.serviceItem}>
            <PaymentIcon className={style.icon} />
            <span className={style.title}>Thanh toán bảo đảm</span>
          </div>
        </Grid>
        <Grid item sm={6} md={3} xs={6}>
          <div className={style.serviceItem}>
            <AutorenewIcon className={style.icon} />{" "}
            <span className={style.title}>Đổi trả miễn phí</span>
          </div>
        </Grid>
        <Grid item sm={6} md={3} xs={6}>
          <div className={style.serviceItem}>
            <WatchLaterIcon className={style.icon} />
            <span className={style.title}>Hỗ trợ 24/7</span>
          </div>
        </Grid>
      </Grid>
      <ProductCategory />
    </div>
  );
}
